### ISSUE TITLE
Feature request: email plz

### ISSUE THREAD

**Issue by faskowit** [alpatania/sassafras#1]
Could sassafras send an email of the top 10 papers (according to relevance)?

**Comment by alpatania** [comment]
As of now the two functions work independently. for some reason if i call the send_email() function from inside save_email() it does not clean the spreadsheet. I will debug next week

**Comment by alpatania** [comment]
It is done. summary.gs can be added as an extra script file. The new sassafras.gs should be used and the variables  send_summary and del_past in sassafras.gs should be put to true
