### ISSUE TITLE
Exception errors causing script to quit

### ISSUE THREAD

**Issue by DoubleKx** [alpatania/sassafras#6]
I was getting SSL exceptions, address unavailable exceptions, and occasionally URL timeout exceptions which were causing the script to terminate midway and not update the google sheet or send an e-mail. I fixed the first by setting 'validateHttpsCertificates' to false and the other exceptions with a try-catch statement. I just set it to send the exception by e-mail but perhaps there's a better way to deal with it.

Inside supporting_code.gs

```
function getStatusCode_(url){
  Logger.log(url);
   var options = {
     'muteHttpExceptions': true,
     'followRedirects': true,
     'validateHttpsCertificates' : false
   };   
   var url_trimmed = url.trim();   
  try {
       var response = UrlFetchApp.fetch(url_trimmed, options);
       return response.getResponseCode();
  } catch(e) {
    //Catch any error here. Example below is just sending an email with the error.
    MailApp.sendEmail('emailAddress', 'Sample Script - Error', e);
  }
```

**Comment by DoubleKx** [comment]
I also set followRedirects to true because the links in the google sheet would have the google scholar portion that did not redirect to the website. It takes a bit longer but it usually places a working link directly in the spreadsheet

**Comment by alpatania** [comment]
Thank you for pointing this out. I will look into it and see if there is a better way to deal with these exceptions.
